sonar.projectKey=Nuri-an_execution-service-api
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.module.ts,src/main.ts,**/*.dto.ts
sonar.qualitygate.wait=true
