import { BadRequestException, ConflictException, NotFoundException } from '@nestjs/common';
import { ExecutionService } from './execution.service';
import { Execution, ExecutionRepository } from './execution.types';
const execution = (status: Execution['status'] = 'QUEUED'): Execution => ({ id: 'execution-1', serviceOrderId: 'order-1', priority: 0, status, createdAt: new Date(), updatedAt: new Date() });
describe('ExecutionService', () => {
  let repository: jest.Mocked<ExecutionRepository>; let audit: { write: jest.Mock }; let publisher: { publish: jest.Mock }; let service: ExecutionService;
  beforeEach(() => { repository = { create: jest.fn(), findById: jest.fn(), findByServiceOrderId: jest.fn(), claimNext: jest.fn(), update: jest.fn() }; audit = { write: jest.fn() }; publisher = { publish: jest.fn() }; service = new ExecutionService(repository, audit, publisher); });
  it('queues an OS and records an audit event', async () => { repository.findByServiceOrderId.mockResolvedValue(null); repository.create.mockResolvedValue(execution()); await expect(service.enqueue('order-1')).resolves.toMatchObject({ status: 'QUEUED' }); expect(audit.write).toHaveBeenCalledWith('EXECUTION_QUEUED', expect.anything()); });
  it('does not queue an OS twice', async () => { repository.findByServiceOrderId.mockResolvedValue(execution()); await expect(service.enqueue('order-1')).rejects.toBeInstanceOf(ConflictException); });
  it('claims the next order and records the responsible mechanic', async () => { const claimed = { ...execution('DIAGNOSING'), assignedTo: 'mechanic-1', startedAt: new Date() }; repository.claimNext.mockResolvedValue(claimed); await expect(service.claimNext('mechanic-1')).resolves.toBe(claimed); expect(audit.write).toHaveBeenCalledWith('EXECUTION_CLAIMED', claimed); });
  it('reports an empty queue', async () => { repository.claimNext.mockResolvedValue(null); await expect(service.claimNext('mechanic-1')).rejects.toBeInstanceOf(NotFoundException); });
  it('rejects a non-existent execution', async () => { repository.findById.mockResolvedValue(null); await expect(service.get('missing')).rejects.toBeInstanceOf(NotFoundException); });
  it('rejects invalid status transitions', async () => { repository.findById.mockResolvedValue(execution('QUEUED')); await expect(service.updateStatus('execution-1', 'COMPLETED')).rejects.toBeInstanceOf(BadRequestException); });
  it('starts repair after a diagnosis and audits it', async () => { const current = { ...execution('DIAGNOSING'), diagnosis: 'broken belt' }; const repairing = { ...current, status: 'REPAIRING' as const }; repository.findById.mockResolvedValue(current); repository.update.mockResolvedValue(repairing); await expect(service.updateStatus('execution-1', 'REPAIRING')).resolves.toBe(repairing); expect(audit.write).toHaveBeenCalledWith('EXECUTION_REPAIRING', repairing); });
  it('requires a diagnosis before repairing', async () => { repository.findById.mockResolvedValue(execution('DIAGNOSING')); await expect(service.updateStatus('execution-1', 'REPAIRING')).rejects.toBeInstanceOf(BadRequestException); });
  it('publishes a completion event after repair', async () => { const repairing = { ...execution('REPAIRING'), diagnosis: 'broken belt' }; const done = { ...repairing, status: 'COMPLETED' as const, completedAt: new Date() }; repository.findById.mockResolvedValue(repairing); repository.update.mockResolvedValue(done); await service.updateStatus('execution-1', 'COMPLETED', { repairNotes: 'belt replaced' }); expect(publisher.publish).toHaveBeenCalledWith('execution.completed', expect.objectContaining({ executionId: done.id, serviceOrderId: done.serviceOrderId })); expect(audit.write).toHaveBeenCalledWith('EXECUTION_COMPLETION_PUBLISHED', done); });
  it('compensates an unfinished execution when the OS is cancelled', async () => { const diagnosing = execution('DIAGNOSING'); const cancelled = { ...diagnosing, status: 'CANCELLED' as const }; repository.findByServiceOrderId.mockResolvedValue(diagnosing); repository.update.mockResolvedValue(cancelled); await expect(service.compensate('order-1', 'approval revoked')).resolves.toBe(cancelled); expect(publisher.publish).toHaveBeenCalledWith('execution.cancelled', expect.objectContaining({ serviceOrderId: 'order-1', reason: 'approval revoked' })); });
  it('does not compensate a completed execution', async () => { repository.findByServiceOrderId.mockResolvedValue(execution('COMPLETED')); await expect(service.compensate('order-1', 'late cancellation')).resolves.toBeNull(); expect(repository.update).not.toHaveBeenCalled(); });
});
