apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: execution-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef: { name: aws-secretsmanager, kind: ClusterSecretStore }
  target: { name: execution-service-secrets }
  data:
    - secretKey: DATABASE_URL
      remoteRef: { key: fiap/execution-service, property: database_url }
    - secretKey: MONGODB_URI
      remoteRef: { key: fiap/execution-service, property: mongodb_uri }
    - secretKey: RABBITMQ_URL
      remoteRef: { key: fiap/execution-service, property: rabbitmq_url }
